Repository CBNU-CMI/cbnu_ulrim, pull requests merged in 2020-11, with the labels that each got.

#4 [#2] router 설정, layout&navigation 제작
  package-lock.json
  package.json
  src/App.tsx
  src/Layout/Layout.module.scss
  src/Layout/Layout.tsx
  src/Layout/index.ts
  src/components/Global/Navigation/Navigation.module.scss
  src/components/Global/Navigation/Navigation.tsx
  src/components/Global/Navigation/index.ts
  src/components/PetitionList/PetitionList.module.scss
  src/components/PetitionList/PetitionList.tsx
  src/components/PetitionList/index.ts
  src/pages/PetitionPage.tsx
  src/pages/index.ts
  src/styles/_palette.scss
  src/styles/global-styles.ts
Labels: front-end

#6 Fix/#5
  .github/ISSUE_TEMPLATE/feature_request.md
  .prettierrc
  package-lock.json
Labels: bug

#7 [#3] navigation event 부여
  src/Layout/Layout.module.scss
  src/Layout/Layout.tsx
  src/components/Global/Navigation/Navigation.module.scss
  src/components/Global/Navigation/Navigation.tsx
  src/components/PetitionList/PetitionList.tsx
  src/components/TodoList/TodoList.module.scss
  src/components/TodoList/TodoList.tsx
  src/components/TodoList/index.ts
  src/pages/TodoListPage.tsx
  src/pages/index.ts
Labels: mark-up

#10 중첩라우팅을 통해 페이지 이동하도록 변경
  src/Layout/index.ts
  src/components/TodoList/TodoList.module.scss
  src/components/TodoList/TodoList.tsx
  src/components/TodoList/index.ts
  src/pages/PetitionPage.tsx
  src/pages/PetitionPage/PetitionPage.module.scss
  src/pages/PetitionPage/PetitionPage.tsx
  src/pages/PetitionPage/index.ts
  src/pages/TodoListPage.tsx
  src/pages/index.ts
Labels: refactor
