Repository CBNU-CMI/cbnu_ulrim, pull requests merged in 2020-12, with the labels that each got.

#22 [#21] refacor: 코드리뷰 바탕으로 수정
  src/App.tsx
  src/components/Global/Navigation/Navigation.module.scss
  src/components/Global/Navigation/Navigation.tsx
  src/elements/Button/Button.tsx
  src/pages/LoginPage/LoginPage.module.scss
  src/pages/LoginPage/LoginPage.tsx
  src/pages/PetitionPage/PetitionPage.module.scss
  src/pages/PetitionPage/PetitionPage.tsx
  src/pages/PollPage/PollPage.tsx
  src/pages/SignupPage/SignupPage.tsx
Labels: refactor

#24 [#20] markup: 아카이브 컴포넌트 제작
  package-lock.json
  package.json
  src/App.tsx
  src/components/Archive/Archive.module.scss
  src/components/Archive/Archive.tsx
  src/components/Archive/index.ts
  src/components/Global/Navigation/Navigation.module.scss
  src/pages/PetitionPage/PetitionPage.module.scss
  src/pages/PetitionPage/PetitionPage.tsx
Labels: mark-up

#30 Feat/#25
  src/App.tsx
  src/components/Archive/Archive.module.scss
  src/components/Global/Navigation/Navigation.module.scss
  src/components/PetitionCard/PetitionCard.module.scss
  src/components/PetitionCard/PetitionCard.tsx
  src/components/PetitionCard/index.ts
  src/components/PetitionList/PetitionList.module.scss
  src/components/PetitionList/PetitionList.tsx
  src/components/PetitionList/mockData.json
  src/pages/PetitionPage/PetitionPage.tsx
Labels: front-end

#32 Feat/#27
  src/components/PetitionList/PetitionList.module.scss
  src/components/PetitionList/PetitionList.tsx
  src/components/Write/Write.module.scss
  src/components/Write/Write.tsx
  src/components/Write/index.ts
  src/pages/PetitionPage/PetitionPage.tsx
Labels: front-end, mark-up

#31 Feat/#28 infinite scroll
  src/components/Login/Login.tsx
  src/components/PetitionList/PetitionList.tsx
  src/components/PetitionList/mockData.json
  src/components/constants.ts
Labels: feature

#41 글쓰기 아이콘 생성
  src/components/Petition/PetitionList/PetitionList.module.scss
  src/components/Petition/PetitionList/PetitionList.tsx
Labels: front-end, mark-up

#40 [#39] feat: 글쓰기 아이콘 생성
  src/components/PetitionList/PetitionList.module.scss
  src/components/PetitionList/PetitionList.tsx
  src/components/Write/Write.module.scss
Labels: feature, front-end

#42 isActive를 이용하여 ExNavLink 리팩토링
  src/components/Global/Navigation/Navigation.module.scss
  src/components/Global/Navigation/Navigation.tsx
Labels: refactor

#43 코드 리팩토링, 리덕스 연결 및 getPetitionList로직 작성
  package-lock.json
  package.json
  src/App.tsx
  src/api/.gitkeep
  src/api/petitionAPI.ts
  src/components/Global/Navigation/Navigation.module.scss
  src/components/Global/Navigation/Navigation.tsx
  src/components/Petition/PetitionList/PetitionList.tsx
  src/components/PetitionCard/PetitionCard.tsx
  src/components/constants.ts
  src/elements/ExNavLink/ExNavLink.tsx
  src/elements/ExNavLink/index.ts
  src/index.tsx
  src/models/.gitkeep
  src/models/Petition.ts
  src/modules/reducers/index.ts
  src/modules/reducers/petitionReducer.ts
  src/modules/reduxStore.ts
  src/modules/selectors/petitionSelector.ts
  src/pages/PollPage/PollPage.tsx
  src/utils/.gitkeep
  src/utils/environmentUtils.ts
  src/utils/reduxUtils.ts
  src/utils/stringUtils.ts
Labels: enhancement, feature
